# Generated by Django 2.2.6 on 2019-10-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_date', models.DateField()),
                ('q_org', models.CharField(max_length=35)),
                ('q_num', models.IntegerField()),
                ('correct_rate', models.FloatField()),
                ('header', models.TextField()),
                ('content', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.Category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.BooleanField()),
                ('example_1', models.TextField(null=True)),
                ('example_2', models.TextField(null=True)),
                ('example_3', models.TextField(null=True)),
                ('example_4', models.TextField(null=True)),
                ('example_5', models.TextField(null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.Subject'),
        ),
    ]
